name: Upload helm chart

on:
  workflow_dispatch:
  push:
    paths:
      - '**/templates'
      - '**/values'

jobs:
  build:
    name: Package & upload charts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Package and push helm charts
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          values=$(echo $ALL_CHANGED_FILES)


