name: Bump chart versions

on:
  push:
    branch:
    - main
    paths:
    - 'charts/**'
    - '!charts/**/Chart.yaml'


jobs:
  build:
    name: Package & upload charts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Update versions
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          set -x
          changed=$(echo $ALL_CHANGED_FILES | tr ' ' '\n')
          changed_values=$(echo "$changed" | grep "values.yaml" | cat)
          changed_charts=$(echo "$changed" | grep "templates" | cut -d '/' -f1 | sort | uniq)

          for item in ${changed_values}; do
            chart=$(dirname $item)
            old_chart_version=$(yq '.version' $chart/Chart.yaml)
            new_version=$(echo $old_chart_version |  awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
            yq -i ".version = \"$new_version\"" $chart/Chart.yaml
            image_tag=$(yq .image.tag $item)
            yq -i ".appVersion = \"$image_tag\"" $chart/Chart.yaml
          done

          for item in ${changed_charts}; do
            old_chart_version=$(yq '.version' $item/Chart.yaml)
            new_chart_version=$(echo $old_chart_version |  awk -F. '/[0-9]+\./{$(NF-1)++;print}' OFS=.)
            yq -i ".version = \"$new_chart_version\"" $chart/Chart.yaml
          done

          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "Updated charts appversion & version"
          git push
