name: Upload helm chart

on:
  workflow_dispatch:
  push:
    paths:
      - 'v49/*'
      - 'v50/*'
      - 'v51/*'

jobs:
  build:
    name: Package & upload charts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Package and push helm charts
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          changed_charts=$(echo $ALL_CHANGED_FILES | cut -d '/' -f1 | sort | uniq )
          for item in ${changed}; do
            chart=$(echo $item | cut -d '/' -f1)
            old_chart_version=$(yq '.version' $chart/Chart.yaml)
            if [[  $item =~ "values.yaml" ]]; then
              yq -i '.version' = $(echo $old_chart_version |  awk -F. '/[0-9]+\./{$NF++;print}' OFS=.) $chart/Chart.yaml
              image_tag = $(yq .images.tag $item)
              yq -i '.appVersion' = $image.tag $chart/Chart.yaml
            fi 
            if [[ $item =~ "templates" ]]; then
              yq -i '.version' = $(echo $old_chart_version |  awk -F. '/[0-9]+\./{$(NF-1)++;print}' OFS=.) $chart/Chart.yaml
            fi
            helm package $chart
          helm repo index --merge index.yaml
          done



