name: Change value poc

on:
  workflow_dispatch:
    inputs:
      image_tag: 
        required: true

jobs:
  build:
    name: Update image tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.OPSFLEET }}
          persist-credentials: true

      - name: update image tag
        shell: bash
        run: | 
          chart_versions_list=$(ls charts)
          tag=${{ inputs.image_tag }}
          version="${tag#[vV]}"
          chart_version="${version%%.*}"
          validate=$(echo "$chart_versions_list" | grep "$chart_version")
          if ! [ -z "$validate" ]; then           
            yq -i '.image.tag = "${{ inputs.image_tag}}"' charts/$validate/values.yaml
            git config --global user.name 'github actions'
            git config --global user.email 'gha@users.noreply.github.com'
            git commit -am "Updated ${validate} with ${{ inputs.image_tag }}"
          else
            echo "${{ inputs.image_tag }} doesn't match available chart versions: $chart_versions_list" 
            exit 1
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: ${{ github.ref }}